### ISSUE TITLE
Why another repo?

### ISSUE THREAD

**Issue by j0k3r** [npotier/sflive-paris-2017#10]
I'm just asking because there is already an organisation with all [Symfony Live](https://github.com/SymfonyLive) talks all over the world.
The Symfony Live 2017 has been created on 29 March 2017.

https://github.com/SymfonyLive/paris-2017-talks/

I think it's best to keep effort in one repository instead of having multiple one.

**Comment by npotier** [comment]
Hi Jérémy you are completly right. I created and tweeted about this repo because I didn't see the "official" repo created  by SymfonyLive. I'll update the Readme to mention it.
